 pipeline {
   agent any
   tools {
     maven "Maven"
     jdk "Java"
   }
   
   stages {
     stage('Build') {
       steps {
         bat 'mvn package deploy -DmuleDeploy'
       }
     }
   }
 }
